### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [btaylor8/edward-noyes-westcott_david-harum#1]
# Semantics

- [x] `Vaterland` should also have `xml:lang="de"`.
- [x] `chapter-27`: I don't think the `went o-f-f` bit calls for `z3998:grapheme` semantics. We use grapheme if someone is spelling out a word, but this looks more to me like someone is drawing a word out. In that case you use [non-break hyphens](https://standardebooks.org/manual/1.7.4/8-typography#8.7.7.6).
- [x] We should restore italics and Latin semantics to `dies non` since it is a [phrase that begins with a word that can be confused for an English word](https://standardebooks.org/manual/1.7.4/8-typography#8.2.9.9).

# Various

- [x] We typically remove the trailing `/` at the end of URLs, e.g. `https://archive.org/details/davidharumstoryo00west/`, `https://github.com/btaylor8/`.

**Comment by weijia-cheng** [comment]
One last thing, you still need to remove the trailing slash in content.opf. Once that is done this will be ready for Alex.

**Comment by btaylor8** [comment]
Sorry about that, not sure how I missed those. I amended the commit since it was the most recent one: 6094f82.
